export const Menu = [
    {
        id : 1 , 
        image : 'images/maggi.jpg' , 
        name  : 'Maggi' , 
        category : 'Breakfast' , 
        price : '$18' , 
        description :'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit hic totam obcaecati dicta vitae quisquam veritatis. Sed, maiores? Libero dolores atque nulla voluptatum molestias est eius obcaecati? Libero amet, tempore illo esse eos iure beatae fugit vitae ipsum totam magni enim iste aut similique unde itaque, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus odio recusandae sed.',
    },
    {
        id : 2 , 
        image : 'images/puri.jpg' , 
        name  : 'Halwa Puri' , 
        category : 'Breakfast' , 
        price : '$12' , 
        description :' dolor est deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus odio recusandae sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temque, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure tem',
    },
    {
        id : 3 , 
        image : 'images/rotiwithmeat.jpg' , 
        name  : 'Roti With Meat' , 
        category : 'Breakfast' , 
        price : '$23' , 
        description :'est deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus odio recusandae sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, iusest deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus odio recusandae sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, ius.',
    },
    {
        id : 4 , 
        image : 'images/samosa.jpg' , 
        name  : 'Somosa' , 
        category : 'Lonch' , 
        price : '$8' , 
        description :'st deserunt illum. Labst deserunt illum. Lab st deserunt illum. Labst deserunt illum. Labst deserunt illum. Labst deserunt illum. Labst deserunt illum. Labst deserunt illum. Labst deserunt illum. Labst deserunt illum. Labst deserunt illum. Labst deserunt illum. Labst deseru.'
    },
    {
        id : 5 , 
        image : 'images/sweet.jpg' , 
        name  : 'Sweet' , 
        category : 'Lonch' , 
        price : '$28' , 
        description :'ndae sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, iusest deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus odio recusndae sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, iusest deserunt ndae sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, iusest deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus odio recus',
    },
    {
        id : 6 , 
        image : 'images/rajmarice.jpg' , 
        name  : 'Berger' , 
        category : 'Lonch' , 
        price : '$7' , 
        description :'est deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus odio rdio recusandae sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, iusndae sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, iusest deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus odio recus.',
    },
    {
        id : 6 , 
        image : 'images/rajmarice.jpg' , 
        name  : 'Rajmarice' , 
        category : 'Lonch' , 
        price : '$7' , 
        description :'est deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus odio rdio recusandae sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, iusndae sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, iusest deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus odio recus.',
    },
    {
        id : 6 , 
        image : 'images/rajmarice.jpg' , 
        name  : 'Rajmarice' , 
        category : 'Lonch' , 
        price : '$7' , 
        description :'est deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus odio rdio recusandae sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, iusndae sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, iusest deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus odio recus.',
    },
    {
        id : 7 , 
        image : 'images/pizza.jpg' , 
        name  : 'Pizza' , 
        category : 'Dinner' , 
        price : '$13' , 
        description :' sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, iusest dndae sed.que, nihil voluptas aullam doloremque, iusto et aut eveniet placeat iure temporibus odio recuseserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus odio recus',
    },
    {
        id : 8 , 
        image : 'images/paubhaji.jpg' , 
        name  : 'Paubhaji' , 
        category : 'Dinner' , 
        price : '$4' , 
        description :'est deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus odio rrunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus odio recusandae sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, ius.',
    },
    {
        id : 8 , 
        image : 'images/momo.jpg' , 
        name  : 'Bara Goost' , 
        category : 'Dinner' , 
        price : '$4' , 
        description :'est deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus odio rrunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus odio recusandae sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, ius.',
    },
    {
        id : 9 , 
        image : 'images/momo.jpg' , 
        name  : 'Momos' , 
        category : 'Evening' , 
        price : '$14' , 
        description :'esed.que, nihil voluillum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus odio rrunt illum. Laborillum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus odio rrunt illum. Laborptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque,lorem  ius.',
    },
    {
        id : 10 , 
        image : 'images/nonvegthali.jpg' , 
        name  : 'Some Thing' , 
        category : 'Evening' , 
        price : '$25' , 
        description :'recusandae sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, iusest deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus recusandae sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, iusest deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus ',
    },
    {
        id : 10 , 
        image : 'images/nonvegthali.jpg' , 
        name  : 'Qorma' , 
        category : 'showarma' , 
        price : '$25' , 
        description :'recusandae sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, iusest deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus recusandae sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, iusest deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus ',
    },
    {
        id : 10 , 
        image : 'images/nonvegthali.jpg' , 
        name  : 'Meat' , 
        category : 'showarma' , 
        price : '$25' , 
        description :'recusandae sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, iusest deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus recusandae sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, iusest deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus ',
    },
    {
        id : 10 , 
        image : 'images/nonvegthali.jpg' , 
        name  : 'Salan' , 
        category : 'showarma' , 
        price : '$25' , 
        description :'recusandae sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, iusest deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus recusandae sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, iusest deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus ',
    },
    {
        id : 10 , 
        image : 'images/nonvegthali.jpg' , 
        name  : 'Showarma' , 
        category : 'showarma' , 
        price : '$25' , 
        description :'recusandae sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, iusest deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus recusandae sed.que, nihil voluptas aliquam dolor est deserunt illum. Laboriosam ullam doloremque, iusest deserunt illum. Laboriosam ullam doloremque, iusto et aut eveniet placeat iure temporibus ',
    }
    
];



